# Copyright (c) 2022 - 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: intel-dgpu-debug
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-dgpu-debug
  namespace: intel-dgpu-debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: intel-dgpu-debug
  namespace: intel-dgpu-debug
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intel-dgpu-debug
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: intel-dgpu-debug
subjects:
- kind: ServiceAccount
  name: intel-dgpu-debug
  namespace: intel-dgpu-debug